# Generated by Django 3.2.19 on 2023-07-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='item',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='yoyal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
