# Generated by Django 3.2.19 on 2023-07-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230705_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='yoyal',
            new_name='total',
        ),
    ]
