# Generated by Django 3.2.19 on 2023-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_yoyal_orderproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
