# Generated by Django 4.2.2 on 2023-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review'),
        ('store', '0019_alter_review_rating'),
    ]

    operations = [
    ]
