# Generated by Django 4.2.2 on 2023-07-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_merge_0015_review_0019_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Нормально'), (2, 'Плохо'), (1, 'Ужасно')]),
        ),
    ]
